apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marcellobot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: marcellobot
      app.kubernetes.io/component: discord-bot
